import '../../data/models/user_model.dart';
import '../../data/models/institute_model.dart';
import '../../data/models/cctv_feed_model.dart';
import '../../data/models/inspection_duty_model.dart';
import '../../data/models/anomaly_model.dart';
import '../../data/models/notification_model.dart';

class MockData {
  // Preconfigured Stakeholder Users
  static const UserModel officialUser = UserModel(
    id: 'USR-HQ-001',
    name: 'Dr. Rajesh Sharma, IAS',
    designation: 'Joint Secretary (Surveillance & Compliance)',
    department: 'Ministry of Social Justice & Empowerment',
    email: 'rajesh.sharma@gov.in',
    phone: '+91 98100 12345',
    role: UserRole.official,
    employeeCode: 'DoSJE-HQ-8821',
    assignedRegion: 'National / All Divisions',
  );

  static const UserModel inspectorUser = UserModel(
    id: 'USR-PMU-104',
    name: 'Anjali Verma',
    designation: 'Senior PMU Inspection Officer',
    department: 'National PMU Quality Audit Cell',
    email: 'anjali.verma@pmu.gov.in',
    phone: '+91 94250 88712',
    role: UserRole.inspector,
    employeeCode: 'PMU-FLD-4402',
    assignedRegion: 'Central Zone (MP, UP & Rajasthan)',
  );

  static const UserModel instituteUser = UserModel(
    id: 'USR-NGO-209',
    name: 'Ramesh Gupta',
    designation: 'Project Director / Incharge',
    department: 'Asha Welfare Rehabilitation Center',
    email: 'ramesh.gupta@ashawelfare.org',
    phone: '+91 98930 77410',
    role: UserRole.institute,
    employeeCode: 'NGO-REG-9914',
    assignedRegion: 'Bhopal District, Madhya Pradesh',
  );

  // Institutes / Projects
  static final List<InstituteModel> institutes = [
    const InstituteModel(
      id: 'INST-001',
      name: 'Asha Welfare Rehabilitation Center',
      scheme: 'Nasha Mukt Bharat (De-addiction)',
      state: 'Madhya Pradesh',
      district: 'Bhopal',
      address: 'Plot 42, Hoshangabad Road, Industrial Area, Bhopal',
      latitude: 23.2599,
      longitude: 77.4126,
      inchargeName: 'Ramesh Gupta',
      inchargePhone: '+91 98930 77410',
      totalEnrolledBeneficiaries: 65,
      activeCameras: 6,
      totalCameras: 6,
      complianceScore: 78.5,
      riskLevel: 'medium',
      isFlaggedForInspection: true,
      lastInspectionDate: '12-May-2026',
    ),
    const InstituteModel(
      id: 'INST-002',
      name: 'Samarth Divyang Skill Institute',
      scheme: 'PM-DAKSH (Skill Development)',
      state: 'Uttar Pradesh',
      district: 'Varanasi',
      address: 'Near BHU Gate 2, Lanka, Varanasi',
      latitude: 25.2677,
      longitude: 82.9913,
      inchargeName: 'Dr. Sunita Dwivedi',
      inchargePhone: '+91 97210 33451',
      totalEnrolledBeneficiaries: 120,
      activeCameras: 8,
      totalCameras: 8,
      complianceScore: 94.0,
      riskLevel: 'low',
      isFlaggedForInspection: false,
      lastInspectionDate: '18-Aug-2026',
    ),
    const InstituteModel(
      id: 'INST-003',
      name: 'Navjeevan Shelter & Livelihood Center',
      scheme: 'SMILE (Livelihood & Enterprise)',
      state: 'Delhi NCR',
      district: 'Central Delhi',
      address: 'Complex 14, Kashmere Gate Transit Camp, New Delhi',
      latitude: 28.6672,
      longitude: 77.2285,
      inchargeName: 'Mohd. Imran Siddiqui',
      inchargePhone: '+91 98112 99014',
      totalEnrolledBeneficiaries: 85,
      activeCameras: 4,
      totalCameras: 6,
      complianceScore: 58.0,
      riskLevel: 'high',
      isFlaggedForInspection: true,
      lastInspectionDate: '04-Feb-2026',
    ),
    const InstituteModel(
      id: 'INST-004',
      name: 'Anand Ashram Vridhjan Seva Kendra',
      scheme: 'Senior Citizen Welfare Homes',
      state: 'Rajasthan',
      district: 'Jaipur',
      address: 'Sector 8, Vidhyadhar Nagar, Jaipur',
      latitude: 26.9610,
      longitude: 75.7760,
      inchargeName: 'Smt. Kamla Pareek',
      inchargePhone: '+91 94140 12789',
      totalEnrolledBeneficiaries: 50,
      activeCameras: 5,
      totalCameras: 5,
      complianceScore: 88.0,
      riskLevel: 'low',
      isFlaggedForInspection: false,
      lastInspectionDate: '22-Jun-2026',
    ),
    const InstituteModel(
      id: 'INST-005',
      name: 'Umeed Drug De-addiction & Care Society',
      scheme: 'Nasha Mukt Bharat (De-addiction)',
      state: 'Punjab',
      district: 'Amritsar',
      address: 'GT Road Byepass, Verka, Amritsar',
      latitude: 31.6340,
      longitude: 74.8723,
      inchargeName: 'Harpreet Singh',
      inchargePhone: '+91 98765 43210',
      totalEnrolledBeneficiaries: 95,
      activeCameras: 3,
      totalCameras: 6,
      complianceScore: 49.0,
      riskLevel: 'high',
      isFlaggedForInspection: true,
      lastInspectionDate: '15-Jan-2026',
    ),
  ];

  // CCTV Feeds
  static final List<CCTVFeedModel> cctvFeeds = [
    const CCTVFeedModel(
      id: 'CAM-001',
      cameraName: 'Gate 1 Entrance & Biometric Desk',
      instituteId: 'INST-001',
      instituteName: 'Asha Welfare Center, Bhopal',
      locationType: 'Main Gate',
      isLive: true,
      fps: 30,
      currentOccupancy: 8,
      isObstructed: false,
      resolution: '1080p FHD',
      aiTags: ['Biometric Check Active', 'Staff Present', 'Normal Flow'],
      streamTimestamp: 'LIVE - 19:24:10 IST',
      motionDetected: true,
    ),
    const CCTVFeedModel(
      id: 'CAM-002',
      cameraName: 'Vocational Training Classroom A',
      instituteId: 'INST-002',
      instituteName: 'Samarth Divyang Institute, Varanasi',
      locationType: 'Classroom',
      isLive: true,
      fps: 28,
      currentOccupancy: 32,
      isObstructed: false,
      resolution: '1080p FHD',
      aiTags: ['Instructor Detected', 'Occupancy: 32/35', 'High Engagement'],
      streamTimestamp: 'LIVE - 19:24:10 IST',
      motionDetected: true,
    ),
    const CCTVFeedModel(
      id: 'CAM-003',
      cameraName: 'Dining Hall & Kitchen Serving Area',
      instituteId: 'INST-003',
      instituteName: 'Navjeevan Shelter, Delhi',
      locationType: 'Dining Hall',
      isLive: true,
      fps: 25,
      currentOccupancy: 42,
      isObstructed: false,
      resolution: '720p HD',
      aiTags: ['Food Distribution', 'Staff Uniform Verified'],
      streamTimestamp: 'LIVE - 19:24:10 IST',
      motionDetected: true,
    ),
    const CCTVFeedModel(
      id: 'CAM-004',
      cameraName: 'Dormitory Hall East Wing',
      instituteId: 'INST-003',
      instituteName: 'Navjeevan Shelter, Delhi',
      locationType: 'Dormitory',
      isLive: false,
      fps: 0,
      currentOccupancy: 0,
      isObstructed: true,
      resolution: 'Offline',
      aiTags: ['Stream Tampered / Blackout Alert', 'Signal Lost 34m ago'],
      streamTimestamp: 'OFFLINE - Alert Sent',
      motionDetected: false,
    ),
    const CCTVFeedModel(
      id: 'CAM-005',
      cameraName: 'Medical Room & Counseling Chamber',
      instituteId: 'INST-001',
      instituteName: 'Asha Welfare Center, Bhopal',
      locationType: 'Office',
      isLive: true,
      fps: 25,
      currentOccupancy: 3,
      isObstructed: false,
      resolution: '1080p FHD',
      aiTags: ['Doctor Available', 'Session In Progress'],
      streamTimestamp: 'LIVE - 19:24:10 IST',
      motionDetected: true,
    ),
    const CCTVFeedModel(
      id: 'CAM-006',
      cameraName: 'Recreation & Common Hall',
      instituteId: 'INST-004',
      instituteName: 'Anand Ashram, Jaipur',
      locationType: 'Classroom',
      isLive: true,
      fps: 30,
      currentOccupancy: 24,
      isObstructed: false,
      resolution: '1080p FHD',
      aiTags: ['Senior Group Activity', 'Caregiver on duty'],
      streamTimestamp: 'LIVE - 19:24:10 IST',
      motionDetected: true,
    ),
    const CCTVFeedModel(
      id: 'CAM-007',
      cameraName: 'Perimeter Gate & Vehicle Entry',
      instituteId: 'INST-005',
      instituteName: 'Umeed De-addiction, Amritsar',
      locationType: 'Main Gate',
      isLive: true,
      fps: 22,
      currentOccupancy: 4,
      isObstructed: false,
      resolution: '720p HD',
      aiTags: ['Guard Post Unattended', 'Security Alert'],
      streamTimestamp: 'LIVE - 19:24:10 IST',
      motionDetected: true,
    ),
  ];

  // Surprise Inspection Duties
  static List<InspectionDutyModel> getInitialInspectionDuties() {
    return [
      InspectionDutyModel(
        id: 'DUTY-2026-901',
        dutyCode: 'DOSJE-INSP-901',
        instituteId: 'INST-001',
        instituteName: 'Asha Welfare Rehabilitation Center',
        schemeName: 'Nasha Mukt Bharat (De-addiction)',
        assignedInspectorId: 'USR-PMU-104',
        inspectorName: 'Anjali Verma',
        deadline: DateTime.now().add(const Duration(hours: 4)),
        status: 'assigned',
        riskReason: 'AI Anomaly: 2 cameras offline + 25% discrepancy in morning biometric attendance.',
        targetLat: 23.2599,
        targetLng: 77.4126,
        currentDistanceMeters: 280.0, // Inspector approaching
        isGeofenceReached: false,
        reportedBeneficiaries: 65,
        checklist: [
          InspectionChecklistItem(
            id: 'CHK-01',
            title: 'Physical gate attendance matches Biometric Logbook',
            category: 'Infrastructure',
            requiresPhoto: true,
          ),
          InspectionChecklistItem(
            id: 'CHK-02',
            title: 'Dormitory cleanliness, bedsheet hygiene, and ventilation',
            category: 'Hygiene & Food',
            requiresPhoto: true,
          ),
          InspectionChecklistItem(
            id: 'CHK-03',
            title: 'All 6 CCTV cameras operational with min 30-day storage',
            category: 'CCTV & Records',
            requiresPhoto: true,
          ),
          InspectionChecklistItem(
            id: 'CHK-04',
            title: 'Diet chart compliance & Kitchen cleanliness audit',
            category: 'Hygiene & Food',
            requiresPhoto: true,
          ),
          InspectionChecklistItem(
            id: 'CHK-05',
            title: 'Direct 1-on-1 beneficiary interaction without staff interference',
            category: 'Beneficiaries',
            requiresPhoto: false,
          ),
          InspectionChecklistItem(
            id: 'CHK-06',
            title: 'Medicine dispensary log & full-time counselor availability',
            category: 'CCTV & Records',
            requiresPhoto: false,
          ),
        ],
      ),
      InspectionDutyModel(
        id: 'DUTY-2026-902',
        dutyCode: 'DOSJE-INSP-902',
        instituteId: 'INST-003',
        instituteName: 'Navjeevan Shelter & Livelihood Center',
        schemeName: 'SMILE (Livelihood & Enterprise)',
        assignedInspectorId: 'USR-PMU-104',
        inspectorName: 'Anjali Verma',
        deadline: DateTime.now().add(const Duration(hours: 8)),
        status: 'assigned',
        riskReason: 'High Risk Score: Tampering alert on East Wing camera + repeated proxy flag.',
        targetLat: 28.6672,
        targetLng: 77.2285,
        currentDistanceMeters: 1450.0,
        isGeofenceReached: false,
        reportedBeneficiaries: 85,
        checklist: [
          InspectionChecklistItem(
            id: 'CHK-01',
            title: 'Verify East Wing camera physical connection & wiring',
            category: 'CCTV & Records',
            requiresPhoto: true,
          ),
          InspectionChecklistItem(
            id: 'CHK-02',
            title: 'Cross-check physical headcount against SMILE portal numbers',
            category: 'Beneficiaries',
            requiresPhoto: true,
          ),
        ],
      ),
      InspectionDutyModel(
        id: 'DUTY-2026-889',
        dutyCode: 'DOSJE-INSP-889',
        instituteId: 'INST-002',
        instituteName: 'Samarth Divyang Skill Institute',
        schemeName: 'PM-DAKSH (Skill Development)',
        assignedInspectorId: 'USR-PMU-104',
        inspectorName: 'Anjali Verma',
        deadline: DateTime.now().subtract(const Duration(days: 2)),
        status: 'completed',
        riskReason: 'Routine quarterly surprise audit.',
        targetLat: 25.2677,
        targetLng: 82.9913,
        currentDistanceMeters: 45.0,
        isGeofenceReached: true,
        reportedBeneficiaries: 120,
        verifiedBeneficiaries: 118,
        inspectorNotes: 'High compliance. Biometric attendance matched physical strength within 2% margin. CCTVs in good working condition.',
        overallRating: 4.8,
        signedBy: 'Anjali Verma (PMU ID: PMU-FLD-4402)',
        completedAt: DateTime.now().subtract(const Duration(days: 2)),
        capturedPhotoTags: ['GPS: 25.2677° N, 82.9913° E', 'Timestamp: 2026-09-01 11:30:15 IST', 'Verified by DoSJE PMU'],
      ),
    ];
  }

  // AI Anomaly Alerts
  static final List<AnomalyModel> anomalies = [
    const AnomalyModel(
      id: 'ANOM-101',
      title: 'Camera Lens Obstructed / Tampered',
      instituteId: 'INST-003',
      instituteName: 'Navjeevan Shelter, Delhi',
      scheme: 'SMILE (Livelihood & Enterprise)',
      type: 'cctv_blackout',
      severity: 'critical',
      timestamp: 'Today, 18:50 IST (34 mins ago)',
      description: 'Dormitory Hall East camera lost video feed abruptly after unnatural motion vibration. Possible tampering or power cutoff.',
      recommendedAction: 'Order immediate surprise physical inspection via PMU or trigger random Video Call.',
    ),
    const AnomalyModel(
      id: 'ANOM-102',
      title: 'Proxy Biometric Punching Detected',
      instituteId: 'INST-001',
      instituteName: 'Asha Welfare Center, Bhopal',
      scheme: 'Nasha Mukt Bharat (De-addiction)',
      type: 'proxy_attendance',
      severity: 'critical',
      timestamp: 'Today, 09:15 IST',
      description: 'AI vision detected 4 distinct fingerprint punch-ins performed by a single individual within 90 seconds.',
      recommendedAction: 'Freeze morning subsidy disbursal and conduct biometric re-verification.',
    ),
    const AnomalyModel(
      id: 'ANOM-103',
      title: 'Beneficiary Headcount Discrepancy',
      instituteId: 'INST-005',
      instituteName: 'Umeed De-addiction, Amritsar',
      scheme: 'Nasha Mukt Bharat (De-addiction)',
      type: 'headcount_mismatch',
      severity: 'warning',
      timestamp: 'Today, 14:30 IST',
      description: 'CCTV AI detected only 51 beneficiaries in meal hall, whereas 95 were marked as present on the portal.',
      recommendedAction: 'Cross-examine food register logs with CCTV timeline clips.',
    ),
    const AnomalyModel(
      id: 'ANOM-104',
      title: 'Supervisory Staff Absence during Operating Hours',
      instituteId: 'INST-005',
      instituteName: 'Umeed De-addiction, Amritsar',
      scheme: 'Nasha Mukt Bharat (De-addiction)',
      type: 'unauthorized_absence',
      severity: 'warning',
      timestamp: 'Today, 16:10 IST',
      description: 'Designated Medical Officer & Warden absent from institute premises for over 4 continuous hours.',
      recommendedAction: 'Issue notice to Project Director.',
    ),
    const AnomalyModel(
      id: 'ANOM-105',
      title: 'Perimeter Geofence Alert: Off-site Punching',
      instituteId: 'INST-004',
      instituteName: 'Anand Ashram, Jaipur',
      scheme: 'Senior Citizen Welfare Homes',
      type: 'geofence_breach',
      severity: 'info',
      timestamp: 'Yesterday, 10:05 IST',
      description: 'Staff mobile attendance punched from 420m away from registered institutional perimeter.',
      recommendedAction: 'Resolved: Staff was attending medical purchase with prior memo.',
      isResolved: true,
    ),
  ];

  // Notifications
  static final List<NotificationModel> notifications = [
    const NotificationModel(
      id: 'NOTIF-01',
      title: 'Surprise Inspection Assigned',
      message: 'AI Assignment Engine has assigned you Duty DOSJE-INSP-901 at Asha Welfare Center, Bhopal. Complete within 4 hours.',
      timestamp: '15 mins ago',
      category: 'inspection',
      isRead: false,
      relatedId: 'DUTY-2026-901',
    ),
    const NotificationModel(
      id: 'NOTIF-02',
      title: 'CRITICAL: Camera Blackout at Navjeevan Shelter',
      message: 'Camera #4 has been dark for 34 mins. Automated anomaly alert dispatched to Joint Secretary.',
      timestamp: '34 mins ago',
      category: 'critical',
      isRead: false,
      relatedId: 'ANOM-101',
    ),
    const NotificationModel(
      id: 'NOTIF-03',
      title: 'Random VC Request Initiated',
      message: 'Central HQ has initiated a surprise Video Conference audit for Classrooms at Samarth Divyang Institute.',
      timestamp: '1 hour ago',
      category: 'cctv',
      isRead: true,
    ),
    const NotificationModel(
      id: 'NOTIF-04',
      title: 'Inspection Report Approved',
      message: 'Your report for Samarth Divyang Institute (DOSJE-INSP-889) was reviewed and approved by Central PMU.',
      timestamp: '1 day ago',
      category: 'compliance',
      isRead: true,
      relatedId: 'DUTY-2026-889',
    ),
  ];
}
